Okay, _really_ converted all Apprentice file line-endings regardless of file xtension

diff --git a/Source Code/Apprentice - 1994/C_C++/comm/Nuntius 1.2/src/Quit•cps b/Source Code/Apprentice - 1994/C_C++/comm/Nuntius 1.2/src/Quit•cps
--- a/Source Code/Apprentice - 1994/C_C++/comm/Nuntius 1.2/src/Quit•cps
+++ b/Source Code/Apprentice - 1994/C_C++/comm/Nuntius 1.2/src/Quit•cps
@@ -1,1 +1,60 @@
-if !"{cps_inited}"	if "{IsShuttingDown}"		Alert "quit¥cps is missing basic definitions, aborting"		exit 1	end	exitendset exit 0If "``rshell -status``"	set exit 0	confirm "You have RShell requests that have not yet completed.  Really Quit?" -t 	If {status} != 0 		exit "-9"	EndEndif !"{IsShuttingDown}" || !"{HasRamDisk}" # bruges til at fjerne RamMPW	set exit 0	SendAE -t ToolServer -e aevtquit ·· dev:null	set exit 1else	SendAE -t ToolServer -e abcdefgh ·· dev:null && RShell -b Flush # only if runningendbegin	echo "begin"	echo "set exit 0";	windows -o	echo "close {mpw}Worksheet ·· dev:null"	echo -n "directory "	directory	echo "end ·· dev:null"end > {mpw}Userstartup¥Windowssave_all -objsclose -a -ycd {mpw}if "{TmpDir}"	if "{HasRamDisk}"		echo -n > {tmp} # avoid "No match for file name pattern" error from MPW_Shell		rm {tmp}[0-9]* # {tmp} {tmp2} {tmp3} ...	else		rm -y {TmpDir}	endendif "{IsShuttingDown}"	if "{HasRamDisk}"		rm -y -i {TmpDir}		if !"{IsMiniEnviroment}"			rm -y -i {RamKilde}			RShell -b {TSF}RamRemoveMPW			exit		end	end	{mpw}Tools:SendAE -e FNDRshut -t Finder -m 1end
+if !"{cps_inited}"
+	if "{IsShuttingDown}"
+		Alert "quit¥cps is missing basic definitions, aborting"
+		exit 1
+	end
+	exit
+end
+
+set exit 0
+
+If "``rshell -status``"
+	set exit 0
+	confirm "You have RShell requests that have not yet completed.  Really Quit?" -t 
+	If {status} != 0 
+		exit "-9"
+	End
+End
+if !"{IsShuttingDown}" || !"{HasRamDisk}" # bruges til at fjerne RamMPW
+	set exit 0
+	SendAE -t ToolServer -e aevtquit ·· dev:null
+	set exit 1
+else
+	SendAE -t ToolServer -e abcdefgh ·· dev:null && RShell -b Flush # only if running
+end
+
+begin
+	echo "begin"
+	echo "set exit 0";
+	windows -o
+	echo "close {mpw}Worksheet ·· dev:null"
+	echo -n "directory "
+	directory
+	echo "end ·· dev:null"
+end > {mpw}Userstartup¥Windows
+
+save_all -objs
+close -a -y
+
+cd {mpw}
+
+if "{TmpDir}"
+	if "{HasRamDisk}"
+		echo -n > {tmp} # avoid "No match for file name pattern" error from MPW_Shell
+		rm {tmp}[0-9]* # {tmp} {tmp2} {tmp3} ...
+	else
+		rm -y {TmpDir}
+	end
+end
+
+if "{IsShuttingDown}"
+	if "{HasRamDisk}"
+		rm -y -i {TmpDir}
+		if !"{IsMiniEnviroment}"
+			rm -y -i {RamKilde}
+			RShell -b {TSF}RamRemoveMPW
+			exit
+		end
+	end
+	{mpw}Tools:SendAE -e FNDRshut -t Finder -m 1
+end
diff --git a/Source Code/Apprentice - 1994/C_C++/lib/stdwin/Conf/makemakefile b/Source Code/Apprentice - 1994/C_C++/lib/stdwin/Conf/makemakefile
--- a/Source Code/Apprentice - 1994/C_C++/lib/stdwin/Conf/makemakefile
+++ b/Source Code/Apprentice - 1994/C_C++/lib/stdwin/Conf/makemakefile
@@ -1,1 +1,102 @@
-#!/bin/sh# makemakefile - create a MakefilePROGNAME=`basename $0`USAGE="usage: $PROGNAME topdir os arch port srcdir builddir"# Check and get arguments#case $# in6)	;;*)  echo "$USAGE" 1>&2    echo '  <src> may be relative to <top>' 1>&2    echo '  <build> may be relative to <top>/Build/<arch>/<port>' 1>&2    exit 2    ;;esacTOPDIR=$1; shiftOS=$1; shiftARCH=$1; shiftPORT=$1; shiftSRCDIR=$1; shiftBLDDIR=$1; shift# Set derived pathnamesCONFDIR=$TOPDIR/Confcase $SRCDIR in/*)	;;*)	SRCDIR=$TOPDIR/$SRCDIR;;esaccase $BLDDIR in/*)	;;*)	BLDDIR=$TOPDIR/Build/$ARCH/$PORT/$BLDDIR;;esacOSPROTO=$CONFDIR/proto.os.$OSARCHPROTO=$CONFDIR/proto.arch.$ARCHPORTPROTO=$CONFDIR/proto.port.$PORTCONFPROTO=$CONFDIR/proto.confSRCPROTO=$SRCDIR/Make.proto# Make sure the source prototype exists, else there's no use in proceeding.# This test is made to avoid creating junk build directories.# (Missing other files are detected by the cat command.)if test ! -f $SRCPROTOthen	echo "$PROGNAME: can't find Makefile prototype $SRCPROTO" 1>&2	exit 1fi# Make sure the build directory exists, create it if necessary# (only one level deep though!)#if test -d $BLDDIRthen	:else	echo "$PROGNAME: creating new build directory $BLDDIR" 1>&2	mkdir $BLDDIR ||	{ echo "$PROGNAME: can't create build directory $BLDDIR" 1>&2; exit 1;}fi# Now begin doing the real work#PRELUDE="$OSPROTO $ARCHPROTO $PORTPROTO $CONFPROTO $SRCPROTO"BOOTMAKE=$BLDDIR/Mf.bootecho "$PROGNAME: creating bootstrap Makefile ..." 1>&2{ echo "TOP=$TOPDIR" &&  cat $PRELUDE;} >$BOOTMAKE ||{ echo "$PROGNAME: can't create bootstrap Makefile $BOOTMAKE" 1>&2; exit 1; }TEMPMAKE=$BLDDIR/Mf.tempecho "$PROGNAME: creating temp Makefile ..." 1>&2{ echo "TOP=$TOPDIR" &&  cat $PRELUDE &&  make -f $BOOTMAKE _bootstrap; } >$TEMPMAKE ||{ echo "$PROGNAME: can't create temp Makefile $TEMPMAKE" 1>&2; exit 1; }MAKEFILE=$BLDDIR/Makefileecho "$PROGNAME: moving temp Makefile to Makefile ..." 1>&2if test -f $MAKEFILEthen	BACKUP=$MAKEFILE.bak	echo "$PROGNAME: NB: moving previous Makefile to backup" 1>&2	rm -f $BACKUP	mv $MAKEFILE $BACKUPfimv $TEMPMAKE $MAKEFILE &&echo "$PROGNAME: done." 1>&2
+#!/bin/sh
+
+# makemakefile - create a Makefile
+
+PROGNAME=`basename $0`
+USAGE="usage: $PROGNAME topdir os arch port srcdir builddir"
+
+# Check and get arguments
+#
+case $# in
+6)	;;
+*)  echo "$USAGE" 1>&2
+    echo '  <src> may be relative to <top>' 1>&2
+    echo '  <build> may be relative to <top>/Build/<arch>/<port>' 1>&2
+    exit 2
+    ;;
+esac
+
+TOPDIR=$1; shift
+OS=$1; shift
+ARCH=$1; shift
+PORT=$1; shift
+SRCDIR=$1; shift
+BLDDIR=$1; shift
+
+
+# Set derived pathnames
+
+CONFDIR=$TOPDIR/Conf
+
+case $SRCDIR in
+/*)	;;
+*)	SRCDIR=$TOPDIR/$SRCDIR;;
+esac
+
+case $BLDDIR in
+/*)	;;
+*)	BLDDIR=$TOPDIR/Build/$ARCH/$PORT/$BLDDIR;;
+esac
+
+OSPROTO=$CONFDIR/proto.os.$OS
+ARCHPROTO=$CONFDIR/proto.arch.$ARCH
+PORTPROTO=$CONFDIR/proto.port.$PORT
+CONFPROTO=$CONFDIR/proto.conf
+SRCPROTO=$SRCDIR/Make.proto
+
+# Make sure the source prototype exists, else there's no use in proceeding.
+# This test is made to avoid creating junk build directories.
+# (Missing other files are detected by the cat command.)
+
+if test ! -f $SRCPROTO
+then
+	echo "$PROGNAME: can't find Makefile prototype $SRCPROTO" 1>&2
+	exit 1
+fi
+
+# Make sure the build directory exists, create it if necessary
+# (only one level deep though!)
+#
+if test -d $BLDDIR
+then
+	:
+else
+	echo "$PROGNAME: creating new build directory $BLDDIR" 1>&2
+	mkdir $BLDDIR ||
+	{ echo "$PROGNAME: can't create build directory $BLDDIR" 1>&2; exit 1;}
+fi
+
+
+# Now begin doing the real work
+#
+PRELUDE="$OSPROTO $ARCHPROTO $PORTPROTO $CONFPROTO $SRCPROTO"
+
+BOOTMAKE=$BLDDIR/Mf.boot
+echo "$PROGNAME: creating bootstrap Makefile ..." 1>&2
+
+{ echo "TOP=$TOPDIR" &&
+  cat $PRELUDE;
+} >$BOOTMAKE ||
+{ echo "$PROGNAME: can't create bootstrap Makefile $BOOTMAKE" 1>&2; exit 1; }
+
+TEMPMAKE=$BLDDIR/Mf.temp
+echo "$PROGNAME: creating temp Makefile ..." 1>&2
+
+{ echo "TOP=$TOPDIR" &&
+  cat $PRELUDE &&
+  make -f $BOOTMAKE _bootstrap; } >$TEMPMAKE ||
+{ echo "$PROGNAME: can't create temp Makefile $TEMPMAKE" 1>&2; exit 1; }
+
+MAKEFILE=$BLDDIR/Makefile
+echo "$PROGNAME: moving temp Makefile to Makefile ..." 1>&2
+
+if test -f $MAKEFILE
+then
+	BACKUP=$MAKEFILE.bak
+	echo "$PROGNAME: NB: moving previous Makefile to backup" 1>&2
+	rm -f $BACKUP
+	mv $MAKEFILE $BACKUP
+fi
+
+mv $TEMPMAKE $MAKEFILE &&
+echo "$PROGNAME: done." 1>&2
